### PR TITLE
Feat/metadata overview

### PR DESCRIPTION
**Pull request by tk-king**
Refactoring of the list page with metadata and labelings added as additional information.
image

### CODE REVIEW

**Comment by TobiasRoeddiger** [comment]
Where did the select boxes go for delete operations?

**Comment by tk-king** [comment]
The wohl card is clickable

**Comment by riedel** [comment]
IMHO, there is quite a lot of white space in the collapsed version. It would be great if unused white space could be used as a preview in the collapsed state (I know it might be a bit difficult to do reactively …)

To explain my use case: if you want to delete all datasets related to a certain set of metadata, you do not want to expand all dataset descriptions.

Just my 2 cents. Otherwise, it looks great!

**Comment by riedel** [comment]
> The whole card is clickable

I think for both usability and accessibility, I would show the check boxes. It makes the interface much more intuitive (you can keep whole thing clickable). Particularly with the collapse also you might to need to really hit everything quite accurately to not trigger the wrong action (Might want to try it on a mobile device: Here a long press would I guess be the typical select op. Short presses for select are typically very annoying)

**Comment by riedel** [comment]
I like this very much!

**Pull request merged**
